import { defineConfig } from 'tsup';

export default defineConfig({
    entry: ['src/index.ts'],
    format: ['esm'],
    outDir: 'dist',
    clean: true,
    dts: true,
    sourcemap: true,
    splitting: false,
    minify: false,
    target: 'es2022',
    banner: {
        js: '// Generated by tsup',
    },
});
